name: First Workflow
on: [push]
  
jobs:
  run-shell-commands:
    runs-on: windows-latest
    steps:
      - name: echo a string
      run: echo "Hello"
      - name: Multiline Command
    run: |
    node -v
    npm -v